services:
  - runtime: docker
    type: web
    name: laravel-app
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:your_app_key_here
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_username
      - key: DB_PASSWORD
        value: your_db_password
    port: 80
    healthCheckPath: /
    autoDeploy: true